version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 1
    labels:
      - dependencies
    commit-message:
      prefix: deps
    groups:
      nuget-version-updates:
        patterns:
          - "*"
      nuget-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 1
    labels:
      - dependencies
    commit-message:
      prefix: ci
    groups:
      github-actions-version-updates:
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
