<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PdfiumNativeVersion>153.0.7988</PdfiumNativeVersion>
    <PdfiumCoreVersion>152.0.7961</PdfiumCoreVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="bblanchon.PDFium.Linux" Version="$(PdfiumNativeVersion)" />
    <PackageVersion Include="bblanchon.PDFium.macOS" Version="$(PdfiumNativeVersion)" />
    <PackageVersion Include="bblanchon.PDFium.Win32" Version="$(PdfiumNativeVersion)" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="FsCheck.Xunit" Version="3.3.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="PDFiumCore" Version="$(PdfiumCoreVersion)" />
    <PackageVersion Include="SkiaSharp" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.10" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
